enum Constants {
    TOGGLE_CENTER_WINDOW = '@@ui/TOGGLE_CENTER_WINDOW',
    CHANGE_BANNER_DIRECTION = '@@ui/CHANGE_BANNER_DIRECTION',
    CHANGE_ACTION_DIRECTION = '@@ui/CHANGE_ACTION_DIRECTION',
}

export default Constants;
